merged erigonos overlay

diff --git a/usr/src/cmd/svc/milestone/fs-joyent b/usr/src/cmd/svc/milestone/fs-joyent
--- a/usr/src/cmd/svc/milestone/fs-joyent
+++ b/usr/src/cmd/svc/milestone/fs-joyent
@@ -11,6 +11,7 @@
 #
 
 #
+# Copyright 2019, Erigones, s. r. o.
 # Copyright 2020 Joyent, Inc.
 #
 
@@ -70,6 +71,33 @@ function mount_zfs
     echo ${output} 1>&2
 }
 
+# Assume the system zpool is zones, but if a different system pool
+# identifies itself (by virtue of the .system_pool file being present in the
+# pool's root dataset), then use that system pool instead.
+SYS_ZPOOL=zones
+
+# Are we booted from HDD? (0/1)
+BOOTED_FROM_HDD=1
+
+# Placeholder for current Boot Environment name
+BENAME="dcos-1"
+
+# Try to determine if we are booted from HDD
+# Do this by finding out whether "/" is being mounted as "zfs"
+mounted "/" "-" "zfs" < /etc/mnttab || BOOTED_FROM_HDD=0
+
+if [ ${BOOTED_FROM_HDD} -ne 0 ]; then
+    BENAME=$(/usr/sbin/beadm list -H | grep ';N' | nawk -F';' '{ print $1 }')
+    # Determine "bootfs" to help us decide whether we run from HDD or not.
+    # bootfs will be "-" if we (most probably) do not run from HDD
+    # This can be also checked with beadm list - XXX
+    bootfs=$(zpool get -H -o value bootfs ${SYS_ZPOOL})
+    [ "x${bootfs}" == "x" ] && fatal "Root pool bootfs property not defined"
+
+    # SYS_ZPOOL is to be determined from bootfs property
+    SYS_ZPOOL=$(echo ${bootfs} | awk -F'/' '{ print $1 }')
+fi
+
 function unlock_pool
 {
     local pool=$1
@@ -92,11 +120,6 @@ function unlock_pool
 if [ $? -ne 0 ]; then
     # If the zpool doesn't exist, then there's nothing to mount.
 
-    # Assume the system zpool is zones, but if a different system pool
-    # identifies itself (by virtue of the .system_pool file being present in the
-    # pool's root dataset), then use that system pool instead.
-    SYS_ZPOOL=zones
-
     # Import specified zpools, or all zpools available
     pools=$(/bin/bootparams | egrep "^zpools?=" | cut -d= -f2 | tr , ' ')
     if [ -z ${pools} ]; then
@@ -113,27 +136,35 @@ if [ $? -ne 0 ]; then
         # Due to early, failed attempts to support the filesystem_limits
         # feature we now need to ensure the dependent feature is enabled.
         zpool set feature@extensible_dataset=enabled $pool
-        if [[ -f /$pool/.system_pool ]]; then
+        if [[ ${BOOTED_FROM_HDD} -ne 1 && -f /${pool}/.system_pool ]]; then
             SYS_ZPOOL=$pool
             [[ "$is_encr" != "off" ]] && kbmadm set-syspool $pool
         fi
     done
 
+#    # Explicitly set features and mount system zpool default dataset
+#    zpool set feature@extensible_dataset=enabled ${SYS_ZPOOL}
+#    zfs mount ${SYS_ZPOOL}
+#
     svccfg -s svc:/system/smartdc/init setprop \
         config/zpool=${SYS_ZPOOL}
     svccfg -s svc:/system/smartdc/init:default refresh
 
-    # If the destroy_zpools boot parameter is set, destroy all zpools
-    /bin/bootparams | grep "^destroy_zpools=true" >/dev/null
-    if [ $? -eq 0 ]; then
-        destroy_zpools
-    fi
+    # Can destroy pools only when running from USB
+    if [ ${BOOTED_FROM_HDD} -eq 0 ]; then
 
-    # A machine is reset to its original unsetup state (i.e. a 'factory reset')
-    # when the smartdc:factoryreset ZFS user property is set on the var dataset.
-    reset=$(zfs get -H -o value smartdc:factoryreset ${SYS_ZPOOL}/var)
-    if [ "${reset}" == "yes" ]; then
-        destroy_zpools
+        # If the destroy_zpools boot parameter is set, destroy all zpools
+        /bin/bootparams | grep "^destroy_zpools=true" >/dev/null
+        if [ $? -eq 0 ]; then
+            destroy_zpools
+        fi
+
+        # A machine is reset to its original unsetup state (i.e. a 'factory reset')
+        # when the smartdc:factoryreset ZFS user property is set on the var dataset.
+        reset=$(zfs get -H -o value smartdc:factoryreset ${SYS_ZPOOL}/var)
+        if [ ${reset} == "yes" ]; then
+            destroy_zpools
+        fi
     fi
 
     # Capture the zpool's status output in the method's log file for
@@ -150,8 +181,18 @@ if [ $? -ne 0 ]; then
         # persistent version after mounting zones/config.
         cp /etc/zones/SUNWdefault.xml /tmp/
 
-        # Mount and configure all system datasets
-        mount_zfs ${SYS_ZPOOL}/var /var
+        if [ ${BOOTED_FROM_HDD} -eq 0 ]; then
+            VARDS="${SYS_ZPOOL}/var"
+            if [[ -n $(/bin/bootparams | grep '^smartos=true') ]]; then
+                mount -F lofs /usbkey/shadow /etc/shadow
+                mount -F lofs /usbkey/ssh /etc/ssh
+            fi
+        else
+            VARDS="${bootfs}/var"
+        fi
+
+        # We are running from USB thus we have to mount some directories read-write
+        mount_zfs "${VARDS}" /var
         mount_zfs ${SYS_ZPOOL}/config /etc/zones
         mount_zfs ${SYS_ZPOOL}/opt /opt
 
@@ -187,13 +228,11 @@ if [ $? -ne 0 ]; then
             mount_zfs ${SYS_ZPOOL}/usbkey /usbkey
         fi
 
-        if [[ -n $(/bin/bootparams | grep '^smartos=true') ]]; then
-            mount -F lofs /usbkey/shadow /etc/shadow
-            mount -F lofs /usbkey/ssh /etc/ssh
+        _swapdev=/dev/zvol/dsk/${SYS_ZPOOL}/swap
+        if ! swap -l | grep -q ^${_swapdev}; then
+            swap -a ${_swapdev} || fatal "failed to configure swap device"
         fi
 
-        swap -a /dev/zvol/dsk/${SYS_ZPOOL}/swap || \
-            fatal "failed to configure swap device"
 
         #
         # Configure the dump device on top of a ZFS volume.  In addition to the
@@ -222,7 +261,7 @@ if [ $? -ne 0 ]; then
                 ${SYS_ZPOOL}/cores/global
         fi
 
-        ln -s /${SYS_ZPOOL}/global/cores /cores
+        [[ ! -d /cores ]] && ln -s /${SYS_ZPOOL}/global/cores /cores
 
         [[ -f /${SYS_ZPOOL}/currbooted ]] && \
             mv /${SYS_ZPOOL}/currbooted /${SYS_ZPOOL}/lastbooted
@@ -230,9 +269,19 @@ if [ $? -ne 0 ]; then
     fi
 fi
 
+if [ ${BOOTED_FROM_HDD} -eq 1 ]; then
+    # Booted from HDD
+    echo "Running from HDD..." > /dev/console
+    exit 0
+elif /bin/bootparams | grep "^netboot=true" > /dev/null; then
+    echo "Running from NET..." > /dev/console
+	exit 0
+else
+    echo "Running from USB..." > /dev/console
+fi
 
-# The rest only applies to the headnode
-/bin/bootparams | grep "^headnode=true" >/dev/null || exit $SMF_EXIT_OK
+# The rest only applies to the headnode and Danube Cloud compute node
+/bin/bootparams | egrep "^(headnode=true|computenode=true)" >/dev/null || exit $SMF_EXIT_OK
 
 # If we rebooted during an upgrade, we're in deep trouble.
 if [ -d /var/upgrade_in_progress ]; then
@@ -275,7 +324,7 @@ function make_usb_copy_if_possible
 
     echo "" > /dev/console
     echo "Moving files from USB boot device onto disk storage." > /dev/console
-    echo "This may take several minutes. Please note the time..." > /dev/console
+    echo "This may take several minutes." > /dev/console
     echo "" > /dev/console
     echo "" > /dev/console
 
diff --git a/usr/src/cmd/svc/milestone/net-physical b/usr/src/cmd/svc/milestone/net-physical
--- a/usr/src/cmd/svc/milestone/net-physical
+++ b/usr/src/cmd/svc/milestone/net-physical
@@ -53,12 +53,26 @@ smf_configure_ip || exit ${SMF_EXIT_OK}
 # Make sure that the libraries essential to this stage of booting can be found.
 LD_LIBRARY_PATH=/lib; export LD_LIBRARY_PATH
 
+# Hard-coded in nictagadm and in other places
+OVERLAY_RULES="/var/run/smartdc/networking/overlay_rules.json"
+
 # Time (in seconds) to wait for admin NIC to get DHCP address before continuing.
 ADMIN_DHCP_TIMEOUT=300
 ActiveAggrLinks=
 typeset -A ActiveAggrLinks
 
 smf_netstrategy
+
+function normalize_mac
+{
+    typeset mac
+
+    mac="$1"
+
+    echo "${mac}" | awk -F':' '{ print $1, $2, $3, $4, $5, $6 }' | { read o1 o2 o3 o4 o5 o6 junk
+        printf "%02x:%02x:%02x:%02x:%02x:%02x" 0x${o1} 0x${o2} 0x${o3} 0x${o4} 0x${o5} 0x${o6}
+    }
+}
 
 function add_active_aggr_links
 {
@@ -388,10 +402,10 @@ function setup_mtu
         curmtu=$(/usr/sbin/dladm show-linkprop -c -o value -p mtu ${link})
         [[ $? -eq 0 ]] && [[ "$curmtu" -eq "${mtus[$mac]}" ]] && continue
 
-            if ! /usr/sbin/dladm set-linkprop -p mtu=${mtus[$mac]} ${link}; then
-                echo "Failed to set mtu to ${mtus[$mac]} for link ${link}"
-                exit $SMF_EXIT_ERR_FATAL
-            fi
+        if ! /usr/sbin/dladm set-linkprop -p mtu=${mtus[$mac]} ${link}; then
+            echo "Failed to set mtu to ${mtus[$mac]} for link ${link}"
+            exit $SMF_EXIT_ERR_FATAL
+        fi
     done
 }
 
@@ -469,9 +483,39 @@ if smf_is_globalzone; then
     fi
 
     # Set up etherstubs
-    for stub in $(echo "${CONFIG_etherstub}" | sed -e "s/,/ /g"); do
-        /usr/sbin/dladm create-etherstub -t $stub || echo "ERROR: could not create etherstub ${stub}."
-    done
+    if [[ -n "${CONFIG_etherstub}" ]]; then
+        typeset -a Etherstubs=(${CONFIG_etherstub//,/ })
+
+        for stub in "${Etherstubs[@]}"; do
+            # Must fail on error (etherstubs are part of SYSINFO_Nic_Tags)
+            /usr/sbin/dladm create-etherstub -t $stub
+        done
+
+        # Reload sysinfo (etherstubs are part of SYSINFO_Nic_Tags)
+        /usr/bin/sysinfo -u
+        load_sdc_sysinfo
+    fi
+
+    # Change MAC addresses
+    if [[ -n "${CONFIG_change_mac}" ]]; then
+        sysinfo_ifaces=$(sysinfo -p | grep "^Network_Interface_.*_MAC_Address" || true)
+
+        for mac_pair in $(echo "${CONFIG_change_mac}" | sed -e "s/;/ /g"); do
+            cur_mac="${mac_pair%,*}"
+            new_mac="${mac_pair#*,}"
+            sysinfo_iface=$(echo "${sysinfo_ifaces}" | grep "$(normalize_mac "${cur_mac}")" || true)
+
+            if [[ -n "${sysinfo_iface}" ]]; then
+                iface=$(echo "${sysinfo_iface}" | cut -d '_' -f 3)
+                echo "changing MAC address of ${iface}: ${cur_mac} -> ${new_mac}"
+                ifconfig "${iface}" ether "${new_mac}"
+            fi
+        done
+
+        # Reload sysinfo
+        /usr/bin/sysinfo -u
+        load_sdc_sysinfo
+    fi
 
     # Create aggregations
     create_aggrs
@@ -527,7 +571,8 @@ if smf_is_globalzone; then
         exit ${SMF_EXIT_ERR_CONFIG}
     fi
 
-    [[ -n "$EARLY_ADMIN" ]] || plumb_admin
+    [[ -z "$EARLY_ADMIN" ]] && [[ -z "${nic_admin_on_etherstub}" ]] && plumb_admin
+    eval "nic_admin_on_etherstub=\${SYSINFO_Etherstub_${SYSINFO_NIC_admin}_NIC_Names}"
 
     # If we performed early configuration of the admin network and
     # the admin interface is on a link aggregation, the aggregation
@@ -551,9 +596,28 @@ if smf_is_globalzone; then
         admin_netmask=${BOOT_admin_netmask}
     fi
 
+    admin_vlan_id=${CONFIG_admin_vlan_id}
+    if [[ -z "$admin_vlan_id" ]]; then
+        admin_vlan_id=${BOOT_admin_vlan_id}
+    fi
+
     admin_ip6=${CONFIG_admin_ip6}
     if [[ -z "$admin_ip6" ]]; then
         admin_ip6=${BOOT_admin_ip6}
+    fi
+
+    if [[ -n "${admin_vlan_id}" ]] || [[ -n "${nic_admin_on_etherstub}" ]]; then
+        if [[ "${admin_vlan_id}" -ne 0 ]]; then
+            admin_vnic_opts="-v ${admin_vlan_id}"
+        else
+            admin_vnic_opts=""
+        fi
+
+        admin_iface_active="admin0"
+        dladm create-vnic -l ${SYSINFO_NIC_admin} $admin_vnic_opts ${admin_iface_active}
+        /sbin/ifconfig ${admin_iface_active} plumb
+    else
+        admin_iface_active="${SYSINFO_NIC_admin}"
     fi
 
     if [[ $admin_ip == 'none' ]]; then
@@ -562,7 +626,7 @@ if smf_is_globalzone; then
         echo 'INFO: admin interface already configured (early setup)'
         ADMIN_NIC_UP=true
     elif [[ -n $admin_ip ]] && [[ -n $admin_netmask ]]; then
-        /sbin/ifconfig ${SYSINFO_NIC_admin} inet ${admin_ip} \
+        /sbin/ifconfig ${admin_iface_active} inet ${admin_ip} \
             netmask ${admin_netmask} up
         ADMIN_NIC_UP=true
 
@@ -576,13 +640,13 @@ if smf_is_globalzone; then
         else
             # We ignore errors here because the most common one is that DHCP is
             # already running.
-            /sbin/ifconfig ${SYSINFO_NIC_admin} dhcp || /bin/true
+            /sbin/ifconfig ${admin_iface_active} dhcp || /bin/true
 
             # Wait for DHCP
             timeout=${ADMIN_DHCP_TIMEOUT}
-            dhcp_admin_ip=$(/sbin/ifconfig ${SYSINFO_NIC_admin} | grep inet | awk '{ print $2 }')
+            dhcp_admin_ip=$(/sbin/ifconfig ${admin_iface_active} | grep inet | awk '{ print $2 }')
             while [[ (-z ${dhcp_admin_ip} || ${dhcp_admin_ip} == "0.0.0.0") && ${timeout} -gt 0 ]]; do
-                dhcp_admin_ip=$(/sbin/ifconfig ${SYSINFO_NIC_admin} | grep inet | awk '{ print $2 }')
+                dhcp_admin_ip=$(/sbin/ifconfig ${admin_iface_active} | grep inet | awk '{ print $2 }')
                 timeout=$((${timeout} - 1))
                 sleep 1
             done
@@ -593,7 +657,7 @@ if smf_is_globalzone; then
 
     if [[ -n ${admin_ip6} && -z "$EARLY_ADMIN" ]]; then
         # Plumb interface for inet6
-        ifconfig ${SYSINFO_NIC_admin} inet6 \
+        ifconfig ${admin_iface_active} inet6 \
             plumb mtu ${CONFIG_admin_mtu:-1500} up
 
         # Autodiscovery IPv6 using SLAAC
@@ -605,7 +669,7 @@ if smf_is_globalzone; then
 
         # Configure static IPv6
         if [[ ${admin_ip6} != "addrconf" ]]; then
-            /sbin/ifconfig ${SYSINFO_NIC_admin} inet6 \
+            /sbin/ifconfig ${admin_iface_active} inet6 \
                 addif ${admin_ip6} preferred up
         fi
 
@@ -620,7 +684,7 @@ if smf_is_globalzone; then
         && [[ ${SYSINFO_Product} == "Parallels Virtual Platform" \
               || ${SYSINFO_Product} == "VirtualBox" ]] \
         && [[ -z $(/usr/sbin/dladm show-bridge -p vmwarebr) ]]; then
-        /usr/sbin/dladm create-bridge -l ${SYSINFO_NIC_admin} vmwarebr
+        /usr/sbin/dladm create-bridge -l ${admin_iface_active} vmwarebr
     fi
 
     # Setup the external NIC. The installer may have already set up external0,
